name: eazy_booking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  shared_preferences: ^2.2.1
  google_fonts: ^5.1.0
  animated_snack_bar: ^0.3.1
  intl: ^0.19.0
  flutter_cupertino_datetime_picker: ^3.0.0

  firebase_auth: ^4.9.0

  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/
